project:
  type: website
  output-dir: docs

website:
  title: "Academic Portfolio"
  favicon: images/ColgateC.png
  sidebar: 
    logo: images/ColgateSeal.png
    style: "docked"
    collapse-level: 1
    search: false
    contents:
      - href: index.qmd
        text: " Home"
        icon: house
      - href: about.qmd
        text: " About"
        icon: person
      - href: ai-use.qmd
        text: " Statement on AI"
        icon: robot
      # MATH 240
      - section: "Computational Statistics"
      # MATH 354
      - section: "Data Analysis 1"
  page-footer:
    left: "© 2026 Colgate University Student Portfolio"
    right: "[GitHub Source](https://github.com/lpwalker)"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
