---
title: "Statement on AI"
bibliography: references.bib
---

In the age where AI is increasingly involved not only in an academic setting, but also in our daily lives, it is both important and necessary to create and follow a personal policy regarding one's AI use. 

There are generally four outcomes when we are faced with a problem in which we might consider using AI to solve [@cipolli]. We can decide against using AI at all, verify its suggestions with our own background knowledge, blindly follow it towards a correct answer, or blindly follow it towards an incorrect answer. I believe that relying on AI for answers where we don't completely understand its sources, methods, or concepts will lead to a society in which humans will lose their autonomy in the workforce, and eventually in their own lives. If we don't do our own thinking, then our functions in the workplace and in academics will become obsolete. 

However, using AI to help us overcome barriers, unexpected issues, or to explain certain concepts that help us along the way of solving a problem can be super beneficial. Rather than spending hours trying to fix a bug that human error may miss, AI can quickly scan an entire file and notice one wrong button that was pressed. Using AI to make our lives more efficient to pave the way for learning, rather than doing the learning for us, is a great way to become an ethical statistical practitioner, as mentioned in the Ethical Guidelines for Statistical Practice [@asa2022]. 

Not only does unethical AI use harm us, it also indirectly harms the people who might rely on our work. Passing work done by AI as your own is both an issue of plaigiarism and responsibility, and others might trust and cite your work as authentic and true, when in reality they are now citing AI [@asa2022]. It is important that we stay honest with the people we collaborate with and disclose all AI use, with plans to remedy any instances of unethical AI use. 